name: Build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y liburing-dev clang
      - run: rustup default stable
      - run: rustup update
      - name: Build
        run: cargo build --verbose